### PR TITLE
LTO toolchains

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by ruslo** [comment]
GCC CI time is about 40 minutes:
```
Generate: 0:02:31.910311s (configure + Hunter 3rd party download/install)
Build: 0:36:01.363913s (just Drishti compile)
Archive creation: 0:00:13.266113s
Test: 0:00:09.340602s
```

**Comment by headupinclouds** [comment]
> GCC CI time is about 40 minutes:

That seems a little long for CI feedback.  I believe the link stage (shared lib or executable) processing w/ `LTO/IPO` is the time consuming part -- more so than the per object file overhead.  My guess is that the total build time will scale somewhat linearly with the total # of `add_executable` calls.  For `CI` testing, it would be sufficient to run `LTO` for all `add_library` targets and one top level `add_executable` target.  All other `add_executable` targets could link without `LTO` (I believe this would be much faster).  `LTO` is specified globally as part of the toolchain by design:

```
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION YES)
```

Is it possible to override the global `CMAKE_INTERPROCEDURAL_OPTIMIZATION` setting with a local target property (in this case disabling `IPO` on a per target basis)?  That would allow us to test `CI` end-to-end, but disable it for most local test targets.

```
option(DO_LOCAL_TEST_LTO "Control local test LTO behavior" OFF)
set_target_properties(test1 PROPERTIES INTERPROCEDURAL_OPTIMIZATION DO_LOCAL_TEST_LTO)
```

**Comment by ruslo** [comment]
> Is it possible to override the global CMAKE_INTERPROCEDURAL_OPTIMIZATION setting with a local target property (in this case disabling IPO on a per target basis)?

Yes should work.

**Comment by headupinclouds** [comment]
I'll make a PR to test it.

**Pull request merged**
