### PR TITLE
glm @ v0.9.9.0; hunter @ v0.23.131

### PR DESCRIPTION
**Pull request by headupinclouds**
see https://github.com/elucideye/drishti/issues/748

### CODE REVIEW

**Comment by headupinclouds** [comment]
`--toolchain libcxx-fpic-hid-sections `

```
In file included from In file included from /home/travis/.hunter/_Base/6421d63/7822cfb/ccc9253/Build/acf/Source/src/lib/acf/acf/ACF.cpp:12:
In file included from /home/travis/.hunter/_Base/6421d63/7822cfb/ccc9253/Build/acf/Source/src/lib/acf/acf/ACF.h:18:
In file included from /home/travis/.hunter/_Base/6421d63/7822cfb/ccc9253/Build/acf/Source/src/lib/acf/acf/MatP.h:17:
In file included from /home/travis/.hunter/_Base/6421d63/7822cfb/ccc9253/Install/include/opencv4/opencv2/core.hpp:54:
In file included from /home/travis/.hunter/_Base/6421d63/7822cfb/ccc9253/Install/include/opencv4/opencv2/core/base.hpp:58:
In file included from /home/travis/.hunter/_Base/6421d63/7822cfb/ccc9253/Install/include/opencv4/opencv2/core/cvstd.hpp:62:
/usr/local/clang-5.0.0/bin/../include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace; did you mean '__signbit'?
using ::signbit;
      ~~^
/usr/include/x86_64-linux-gnu/bits/mathinline.h:139:8: note: '__signbit' declared here
__NTH (__signbit (double __x))
```

**Comment by headupinclouds** [comment]
`android-ndk-r18b-api-24-arm64-v8a-clang-libcxx11`

```
-- [hunter *** DEBUG *** 2019-04-22T17:11:57] load: /home/travis/.hunter/_Base/Download/Hunter/0.23.155/6421d63/Unpacked/cmake/projects/Boost/system/hunter.cmake ... end
-- Found Boost 1.70.0 at /home/travis/.hunter/_Base/6421d63/f2cf786/487d293/Install/lib/cmake/Boost-1.70.0
--   Requested configuration: REQUIRED COMPONENTS system;filesystem
CMake Error at /home/travis/.hunter/_Base/6421d63/f2cf786/487d293/Install/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Could not find a package configuration file provided by "boost_system"
  (requested version 1.70.0) with any of the following names:

    boost_systemConfig.cmake
    boost_system-config.cmake

  Add the installation prefix of "boost_system" to CMAKE_PREFIX_PATH or set
  "boost_system_DIR" to a directory containing one of the above files.  If
  "boost_system" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /home/travis/.hunter/_Base/6421d63/f2cf786/487d293/Install/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  src/CMakeLists.txt:181 (find_package)
```

**Comment by headupinclouds** [comment]
`TOOLCHAIN=osx-10-13`

```
[00:35:09]   C:\projects\drishti\src\lib\drishti\face\Face.cpp(17): fatal error C1083: Cannot open include file: 'opencv2/videostab/global_motion.hpp': No such file or directory [C:\projects\drishti\_builds\vs-14-2015-sdk-8-1\src\lib\drishti\drishti_world.vcxproj]
[00:35:09]   C:\projects\drishti\src\lib\drishti/face/FaceDetectorAndTrackerImpl.h(19): fatal error C1083: Cannot open include file: 'opencv2/videostab/global_motion.hpp': No such file or directory [C:\projects\drishti\_builds\vs-14-2015-sdk-8-1\src\lib\drishti\drishti_world.vcxproj]
[00:35:09]   C:\projects\drishti\src\lib\drishti/face/FaceDetectorAndTrackerImpl.h(19): fatal error C1083: Cannot open include file: 'opencv2/videostab/global_motion.hpp': No such file or directory [C:\projects\drishti\_builds\vs-14-2015-sdk-8-1\src\lib\drishti\drishti_world.vcxproj]
[00:35:09]   C:\projects\drishti\src\lib\drishti/face/FaceDetectorAndTrackerImpl.h(19): fatal error C1083: Cannot open include file: 'opencv2/videostab/global_motion.hpp': No such file or directory [C:\projects\drishti\_builds\vs-14-2015-sdk-8-1\src\lib\drishti\drishti_world.vcxproj]
[00:35:09]   C:\projects\drishti\src\lib\drishti/face/face_util.h(17): fatal error C1083: Cannot open include file: 'opencv2/videostab.hpp': No such file or directory [C:\projects\drishti\_builds\vs-14-2015-sdk-8-1\src\lib\drishti\drishti_world.vcxproj]
[00:35:09]   C:\projects\drishti\src\lib\drishti/face/face_util.h(17): fatal error C1083: Cannot open include file: 'opencv2/videostab.hpp': No such file or directory [C:\projects\drishti\_builds\vs-14-2015-sdk-8-1\src\lib\drishti\drishti_world.vcxproj]
```

**Comment by headupinclouds** [comment]
`android-ndk-r18b-api-24-arm64-v8a-clang-libcxx11`

It seems to want to use boost 1.70.0 even though the local config specifies a different version.

https://github.com/elucideye/drishti-upload/blob/test/config.cmake#L270


```
-- Found Boost 1.70.0 at /home/travis/.hunter/_Base/6421d63/f2cf786/4aab71b/Install/lib/cmake/Boost-1.70.0
--   Requested configuration: REQUIRED COMPONENTS system;filesystem
CMake Error at /home/travis/.hunter/_Base/6421d63/f2cf786/4aab71b/Install/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Could not find a package configuration file provided by "boost_system"
  (requested version 1.70.0) with any of the following names:

    boost_systemConfig.cmake
    boost_system-config.cmake

  Add the installation prefix of "boost_system" to CMAKE_PREFIX_PATH or set
  "boost_system_DIR" to a directory containing one of the above files.  If
  "boost_system" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /home/travis/.hunter/_Base/6421d63/f2cf786/4aab71b/Install/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  src/CMakeLists.txt:181 (find_package)
```

**Comment by ruslo** [comment]
> CMake Error at /home/travis/.hunter/_Base/6421d63/f2cf786/4aab71b/Install/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):

I was able to reproduce it with 5243b4c commit but can't reproduce it with stand-alone example, checking.

**Comment by headupinclouds** [comment]
> I was able to reproduce it with 5243b4c commit but can't reproduce it with stand-alone example, checking.

Same here.

**Comment by ruslo** [comment]
> CMake Error at /home/travis/.hunter/_Base/6421d63/f2cf786/4aab71b/Install/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):

Should be better with https://github.com/ruslo/hunter/releases/tag/v0.23.159

**Pull request merged**
