### PR TITLE
CI testing on Android emulator

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by ruslo** [comment]
Android on Linux with emulator:
```
OSError: [Errno 28] No space left on device
```

**Comment by headupinclouds** [comment]
> OSError: [Errno 28] No space left on device

Can you provide some context for this error?  Does this occur while a  particular test is tuning?

**Comment by ruslo** [comment]
Android emulator require to install extra SDK component. I guess emulator itself require some disk space too while running. We have this error before test started.

**Comment by ruslo** [comment]
OSX image has enough disk space, emulator works:
* https://travis-ci.com/elucideye/drishti/jobs/75515782

**Comment by ruslo** [comment]
> OSX image has enough disk space, emulator works

I guess there are few disk space optimizations possible (in SDK, in Hunter, in emulator), research needed. For now I'm excluding Linux + Android and leaving OSX + Android only.

**Comment by ruslo** [comment]
Branch `master` inconsistent:
```
Submodule path 'src/3rdparty/xgboost': checked out '05fc548e53b63bdd2d80c8fb3e9a6d0e428424d1'
Unable to checkout '393a3dfc63986e877ad0ba16b5d34d4325f34ffa' in submodule path 'src/3rdparty/ogles_gpgpu'
```
* https://travis-ci.com/elucideye/drishti/jobs/75511641

Something happened with ogles submodule I guess...

**Comment by headupinclouds** [comment]
Sorry.  Should be fixed now: `393a3dfc fix case of find_package calls (linux errors)`

**Pull request merged**
