### PR TITLE
add private drishti_gltest library for portable windowless opengl context

### PR DESCRIPTION
**Pull request by headupinclouds**
A number of changes related to gpu testing, related code and cmake cleanup, the ogles_gpgpu dependency, and silent GTest logs

* Add drishti_gltest for portable windowless GLContext
  + GLFWContext : public GLContext (NOT (IOS OR ANDROID))
  + QGLContext : public GLContext
* global query replace in filenames, C++, and CMakeLists.txt: ’s/qtplus/gltest/g’
* disable qt + mobile (IOS OR ANDROID) GPU gtests for drishti_{hci,acf,drishti}
* control clang formatting w/ on/off switches
* disable logging during gtests
  + add —silent option to turn loggin goff
  + add option to name logger for FaceTracker
  + remove unused threshold shader param for Nms2
* add simple test-ogles_gpgpu for ogles_gpgpu sanity test (link, etc)
* ogles_gpgpu package: add find_dependency(OpenGL)
* prefer lower case for local (i.e. not option) vars in some cases
* rework some preprocessor logo: prefer `#if defined(SOME_DEFINE)` to `#if SOME_DEFINE` (is 0 or NOT)
* indentation fixes and formatting guards `// clang-format {off,on} `

### CODE REVIEW

**Comment by headupinclouds** [comment]
Clean PR + fixes origin/context == #446

**Comment by headupinclouds** [comment]
Status: OpenGL linking + testing works locally, but it seems the context creation is failing for CI tests. I'll improve testing in the ogles_gpgpu layer, and will investigate GPU allocation/handling on Travis + Appveyor.

**Comment by headupinclouds** [comment]
GPU testing isn't currently supported on travis:
https://github.com/travis-ci/travis-ci/issues/5911
https://github.com/travis-ci/travis-ci/issues/5911#issuecomment-293615127

**Comment by headupinclouds** [comment]
GLFW should provide a CPU rendering context using mesa, as of this commit:

https://github.com/glfw/glfw/issues/281#issuecomment-283162003

We can do:

```
glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_OSMESA_CONTEXT_API)
```

It will search for libMesa.{dylib,so}.  Will this be compatible with `glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);`? 

Note: 

> OSMesa: As its name implies, an OpenGL context created with OSMesa does not update the window contents when its buffers are swapped. Use OpenGL functions or the OSMesa native access functions glfwGetOSMesaColorBuffer and glfwGetOSMesaDepthBuffer to retrieve the framebuffer contents

Installing libMesa from source (autoconf) on Mac OS Sierra is not trivial.

https://mesa.freedesktop.org/archive/mesa-17.0.0-rc1.tar.gz

**Comment by ruslo** [comment]
> Installing libMesa from source (autoconf) on Mac OS Sierra is not trivial

Same for Linux, this is the reason why we have to run `apt-get install libgl1-mesa-dev`. I can take a look if we need this in Hunter though.

**Comment by headupinclouds** [comment]
> Will this be compatible with glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);

It may not be possible.  Even on ubuntu where mesa can be installed easily, `glfwInit()` fails. This post suggests a window based`ssh -X` connection is required.

 https://github.com/glfw/glfw/issues/696#issuecomment-176353504

I'll do some more digging.

**Comment by headupinclouds** [comment]
http://stackoverflow.com/q/35092531

**Comment by headupinclouds** [comment]
> This recent Mesa extension - MESA_platform_surfaceless - provides a native display independent of any native window system. Given this solution already works and is testable via CI, we can pursuit this as a follow-up work.

https://github.com/mapbox/mapbox-gl-native/issues/7020#issue-188742720

**Comment by headupinclouds** [comment]
Portable SW only OpenGL + CI testing (without GPU) will require a bit more work.  There seem to be at least two different approaches for this, both of which rely on Mesa3D.  I've experimented with each, starting on an Ubuntu Trusty server, and haven't yet managed to get either one working.  These are roughly outlined below:

Approach 1: GLFW + MESA 
* `glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE)` + `glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_OSMESA_CONTEXT_API)` + `Xvfb` (local x SW X server) 
* seems to be the approach used by mapbox folks for OpenGL CI testing
* Tested on Ubuntu Trusty but seemed to hit an `Xvfb` error

Approach 2: MESA w/  EGL_MESA_platform_surfaceless
* http://www.phoronix.com/scan.php?page=news_item&ppx=mesa-surfaceless-spec
* https://github.com/mapbox/mapbox-gl-native/issues/7020

The core issue of CI + OpenGL testing is somewhat orthogonal to the changes in this PR.  I'll disable OpenGL tests for CI builds (relying on local OpenGL testing for now) so this PR can be merged.  I'll create a separate issue to track the CI + OpenGL requirements above.  Ideally, this will be a separate library that can be shared by drishti and ogles_gpgpu.  It may be some combination of:

* https://github.com/Uroc327Mirrors/mesa3d : EGL_MESA_platform_surfaceless ...
* https://github.com/glfw/glfw: (OS X, Linux, MSVC)
* https://github.com/brackeen/glfm (iOS, Android)

**Pull request merged**
