### PR TITLE
[WIP] use 'drishti_assets' package

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by ruslo** [comment]
How this logic should changed:
* https://github.com/elucideye/drishti/blob/d4e1c896f78174e4f51fb6a1e4cc0fb9bc6f1148/cmake/Modules/drishti_set_unit_test_assets.cmake#L8-L19
?

Everything except `cpb` should be removed? Do we need this module at all?

**Comment by headupinclouds** [comment]
Since the imported `drishti_assets` package will be exporting variables required for testing, I don't think we really need this any longer.

**Comment by ruslo** [comment]
These files not installed by `drishti_assets`:
* https://github.com/elucideye/drishti/blob/d4e1c896f78174e4f51fb6a1e4cc0fb9bc6f1148/src/examples/integration/CMakeLists.txt#L84-L85

Add them?

**Comment by headupinclouds** [comment]
The proper fix is to add the images + associated xml/json files to the test data here (those ones slipped through the cracks):

https://github.com/elucideye/drishti-faces

That contains some face data for simple tests (needs ground truth).  We can add packages for other common data sets to hunter later (FDDB, LFW, etc).

**Comment by headupinclouds** [comment]
Closing after merge of #482

**Pull request closed without merging**
