### PR TITLE
add public/relocatable src/examples tree (native iOS + Android)

### PR DESCRIPTION
**Pull request by headupinclouds**
This PR is the first major refactoring to provide real-time eye tracking native applications for iOS and Android platforms.  The applications are native in the sense that they make direct use of the mobile platform SDK's at the top application layer, and they will effectively replace the cross platform Qt/QML facefilter demo application.  Most of the core processing remains native C/C++ and OpenGL, with a minimal platform specific application layer: Android=Java, iOS=Swift.  This should radically reduce build times (compared to the Qt facefilter app), will be CI friendly, and will hopefully make the project accessible to more users.  Another benefit is that the manual camera config files required in facefilter (intrinsic params, etc) are no longer necessary, as the relevant parameters are queried from the mobile SDK directly.

The iOS application uses a CMake generated project, and for top level in-repo project builds, it is effectively just another `add_executable()` CMake application.  The top level application layer uses Swift with simple bindings (bridging header, etc) to the C/C++ drishti libs.  This application feeds the drishti native layer with an OpenGL texture stream from the application layer using an AVFoundation Camera in combination with Swift managed iOS Texture Caches.

In Android, the roles are reversed.  The build is still based on CMake, but Android Studio/Gradle manages it directly.  The Android Studio build is based on @rulso's [android-studio-with-hunter](https://github.com/forexample/android-studio-with-hunter) example, and that project has links for documentation associated with injecting Hunter into the Android Studio toolchain correctly.  It requires Android Studio 3.2 beta for external CMake support (i.e., not the non-standard CMake bundled with Android Studio).  This CMake support is a huge milestone, as it let's us build our projects in Android Studio with Hunter, which wasn't practical with the previous bundled CMake.  The Android application uses the Camera 2 API in combination with an Android/Java SurfaceTexture, for efficient conversion of OpenGL textures.  The created texture are of type ` GL_TEXTURE_EXTERNAL_OES ` and can be managed in the drishti native modules directly w/ `ogles_gpgpu`.

There are two different build modes for these applications: 1) a top level in-repo build tree mode, where the drishti C++ libraries are "bundled" with the application project directly; 2) a package build, where the applications use drishti as a CMake package managed through Hunter.  By default, the later will be accomplished from the current in-repo commit using the [GIT_SELF](https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-self.html) `hunter_config()` option.  

A generic "desktop" application example using `cv::VideoCapture` and `glfw` will be added in the same application tree for development purposes.

TODO:

* CI config updates
* README notes for iOS + Android app (addressed partly by above)

Commit summary:

* migrate src/app/sdk to src/examples and update paths appropriately
* migrate (most of) drishti/cmake to drishti/src/examples/cmake (sufficient for *copyable* stand-alone build tree)
* add reusable CMake project init.cmake refactoring from @ruslo
* update HunterGate
* update drishti-upload to make use of `DRISHTI_{DRISHTI,ACF}_AS_{SELF,SUBMODULE}`, et c
* specify ios/swift langauge version at top of project
* Fix OpenGL ES 3.0 for iOS: remove invalid include <OpenGLES/ES2/glext2.h>
* remove old src/examples stuff
* remap DRISHTI_BUILD_EXAMPLES to toggle public/relocatable src/examples code
* add DRISHTI_BUILD_UTILITIES option for internal/private src/app code
* use DRISHTI_CMAKE_ROOT_DIR consistently for all cmake and drishti-upload paths
* remove unused

Relates to the following issues:
https://github.com/elucideye/drishti/issues/696
https://github.com/elucideye/drishti/issues/685
https://github.com/elucideye/drishti/issues/665
https://github.com/elucideye/drishti/issues/639
https://github.com/elucideye/drishti/issues/578

### CODE REVIEW

**Comment by headupinclouds** [comment]
Linux VM's with *android* toolchain builds are running out of space.  A fair amount of CI size reduction work has already been done, but we can also try the `minimal` image as suggested here https://docs.travis-ci.com/user/common-build-problems/#im-running-out-of-disk-space-in-my-build

**Comment by ViktorSkabiak** [comment]
Hi guys. I've just tried to build src/examples/facefilter/android-studio project with Android Studio 3.3, and I've got an error related to Cmake version. It says the minimal required Cmake version 3.9 but actually Android Studio SDK manager allows to install only Cmake 3.6 version. Help me please with this issue. Thanks)) 
Error Screenshot: image

SDK manager: image

**Comment by ruslo** [comment]
@matejsteinbacher Yes, Ninja is a requirement. I have updated [documentation](https://docs.hunter.sh/en/latest/faq/android-studio.html), thanks.

**Comment by headupinclouds** [comment]
Some build notes here https://github.com/elucideye/drishti/blob/master/README.rst#news-20180810 along with some clarification about the `GIT_SELF` feature.  Summary: With the latest [commit](https://github.com/elucideye/drishti/commit/e66dd1ca464c8e6d412b79d29582be920d9a0133) you should be able to build from the top level `drishti/android-studio` directory for "bundled source" builds, or `drishti/src/examples/facefilter/android-studio` for hunter package drishti use (via `GIT_SELF`) per @ruslo's original CMake logic.

**Comment by matejsteinbacher** [comment]
@ruslo Glad to have helped. One more note: in the documentation, it's written: "You may want to add the paths to Android NDK/SDK as well". Well, both paths are required (it's what otherwise Android Studio would do), but the way it's written may be understood as an option. And the file should be at the gitignore because the content is specific to a local machine.

**Comment by ruslo** [comment]
> both paths are required (it's what otherwise Android Studio would do)

> the file should be at the gitignore because the content is specific to a local machine

@matejsteinbacher Both notes added: https://docs.hunter.sh/en/latest/faq/android-studio.html

**Pull request merged**
