### PR TITLE
Use frameworks from Hunter

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by ruslo** [comment]
Android test failed:
```
7: *** BEGIN ***
7: [==========] Running 2 tests from 1 test case.
7: [----------] Global test environment set-up.
7: [----------] 2 tests from HCITest
7: [ RUN      ] HCITest.RunTestCPUAsync
7: Segmentation fault
7: 139
7: *** END ***
7: CMake Error at _3rdParty/gauze_test/DrishtiHciTest.cmake:156 (message):
7:   Command exits with error code: 139
7:
7:

 7/14 Test  #7: DrishtiHciTest ........................***Failed   26.87 sec
```
probably submodules are not synchronized correctly

**Comment by headupinclouds** [comment]
... and only for `TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections-lto`.  I will take a look.

**Comment by ruslo** [comment]
Android restarted, may be it's a glitch? :)

**Comment by headupinclouds** [comment]
This is reproducible on my laptop using the current android toolchain from travis + android emulator.  I've tried `std::cout` based debugging, but the error disappears with additional logging.  Maybe asan or gdb will help with emulator debugging (it requires a rooted device otherwise).

**Comment by headupinclouds** [comment]
So far I've only been able to reproduce this error while running on the emulator (OS X host) with the android LTO toolchain in MinSizeRel configuration with this build config (from travis):

```
#!/bin/bash

TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections-lto
CONFIG=MinSizeRel
#CONFIG=Debug
INSTALL=--strip

ARGS=(
    --toolchain ${TOOLCHAIN}
    --config ${CONFIG}
    --verbose
    --ios-multiarch --ios-combined
    --fwd
    DRISHTI_BUILD_REGRESSION_SIMD=NO
    DRISHTI_BUILD_REGRESSION_FIXED_POINT=NO
    DRISHTI_COPY_3RDPARTY_LICENSES=ON
    GAUZE_ANDROID_USE_EMULATOR=YES
    HUNTER_USE_CACHE_SERVERS=YES
    HUNTER_DISABLE_BUILDS=NO
    HUNTER_CONFIGURATION_TYPES=${CONFIG}
    HUNTER_SUPPRESS_LIST_OF_FILES=ON
    --test
    --archive drishti
    --jobs 2
    ${INSTALL}
)

polly.py ${ARGS[@]} --reconfig
```

The same build on a real device does not exhibit the problem.

If I run on the emulator w/ the same build except for CONFIG=Debug there is no error.

I've noticed that adding or removing `std::cout` logging can hide or trigger the error.

With the android LTO builds plus we do see these types of errors w/ the binary cache dependencies:

```
/Users/travis/build/elucideye/drishti-upload/_ci/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_ios.h:66:11: warning: type 'struct basic_ios' violates one definition rule  
/Users/dhirvonen/pkg/ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_ios.h:66:11: note: a type with the same name but different layout is defined in another translation unit
     class basic_ios : public ios_base
```

Which is probably unrelated, but seems worth mentioning.

**Comment by headupinclouds** [comment]
This is the direct ACF test that failed in one build.  After changing `std::cout` it no longer fails.  Repeating the test for multiple images sizes `for(int i = 512; i < 1024; i++) ` (as shown below) does not trigger the error:

```
TEST_F(ACFTest, ACFDetectionCPUMat)
{
    WaitKey waitKey;

    auto detector = getDetector();
    ASSERT_NE(detector, nullptr);

    std::vector<double> scores;
    std::vector<cv::Rect> objects;
    detector->setIsTranspose(false);

    for(int i = 512; i < 1024; i++) // <=== NEW
    {
        cv::Mat image;
        cv::resize(m_I, image, {i, i});
        (*detector)(m_I, objects, &scores);                
        (*detector)(image, objects, &scores);
    }
/// SNIP
```

I've also tried the full test suite in `OS X` with the same travis build command and `CONFIG=MinSizeRel TOOLCHAIN=osx-10-12-sanitize-address-hid-sections INSTALL=--install` without any luck triggering the error.

The `iostream` sensitivity is the only clue I've seen so far.

**Comment by headupinclouds** [comment]
I'm fairly sure this is due to an out of bounds read in a look up table from the ACF toolbox package:

https://github.com/elucideye/drishti/blob/pr.framework/src/lib/drishti/acf/toolbox/gradientMex.cpp#L134
```
    float operator[](int i) const
    {
#if DRISHTI_DEBUG_ACOS_TABLE
        CV_Assert(((i + n + b) >= 0) && ((i + n + b) < n * 2 + b * 2));
#endif
        return a1[i]; // <== out of bounds read here
    }
```

I expect it is due to uninitialized memory (or something similar) and expect to have a fix later today.

**Comment by headupinclouds** [comment]
The latest commit should fix the issue.  It was showing up in the Android Emulator due to FPU behavior that triggered an array index out of bounds error in a lookup table optimization step that occurs as part of ACF gradient histogram computation.  I've added a SIMD clamp to limit the orientation index explicitly.  I don't expect there will be any impact on speed here.  I think Address Sanitizer (running in the Android Emulator) would likely have caught this:

https://github.com/google/sanitizers/wiki#addresssanitizer 

In polly we have `sanitize-address.cmake` and `osx-*sanitize-address*.cmake`.  `iOS` is covered to some extent for local project source via the generated Xcode project `[] address sanitizer` checkbox in the target specific scheme "Diagnostics" sections.  It would be nice to have coverage for Android.  I'll create an issue for a functional Android Address sanitizer.  I've seen comments in the ndk issues that this still requires a rooted device, and that limitation is being addressed in future versions, but that it should work with Android Emulator (as far as I can tell).  I believe it is also limited to `llvm` toolchains (not the current gcc), which is fine for debugging builds, and will eventually be the default anyway.

**Comment by headupinclouds** [comment]
Thanks

**Pull request merged**
